service: pwa-ssr
runtime: nodejs10

automatic_scaling:
  max_idle_instances: 1

default_expiration: "0s"

handlers:
  # Cache forever (thanks to fingerprinting)
  - url: /_next/static
    static_dir: .next/static
    expiration: "365d"
    http_headers:
      Vary: Accept-Encoding

  # Special case caching
  - url: /service-worker.js
    static_files: .next/service-worker.js
    upload: .next/service-worker.js
    http_headers:
      Vary: Accept-Encoding

  - url: /favicon.ico
    static_files: public/favicon.ico
    upload: public/favicon.ico
    expiration: "7d"
    http_headers:
      Vary: Accept-Encoding

  - url: /manifest.json
    static_files: public/manifest.json
    upload: public/manifest.json
    expiration: "1d"
    http_headers:
      Vary: Accept-Encoding

  - url: /robots.txt
    static_files: public/robots.txt
    upload: public/robots.txt
    expiration: "1d"
    http_headers:
      Vary: Accept-Encoding

  # Catch all other public files (long cache)
  - url: /(.*\..+)$
    static_files: public/\1
    upload: public/.*$
    expiration: "7d"
    http_headers:
      Vary: Accept-Encoding

  # Application dynamic routes
  - url: /.*
    script: auto
