// App
export const SET_HISTORY_STATE = "SET_HISTORY_STATE";

// Fetching
export const FETCH_YEAR_EVENTS_REQUEST = "FETCH_YEAR_EVENTS_REQUEST";
export const FETCH_YEAR_EVENTS_SUCCESS = "FETCH_YEAR_EVENTS_SUCCESS";
export const FETCH_YEAR_EVENTS_ERROR = "FETCH_YEAR_EVENTS_ERROR";
export const FETCH_EVENT_REQUEST = "FETCH_EVENT_REQUEST";
export const FETCH_EVENT_SUCCESS = "FETCH_EVENT_SUCCESS";
export const FETCH_EVENT_ERROR = "FETCH_EVENT_ERROR";
export const FETCH_EVENT_MATCHES_REQUEST = "FETCH_EVENT_MATCHES_REQUEST";
export const FETCH_EVENT_MATCHES_SUCCESS = "FETCH_EVENT_MATCHES_SUCCESS";
export const FETCH_EVENT_MATCHES_ERROR = "FETCH_EVENT_MATCHES_ERROR";
export const FETCH_EVENT_ALLIANCES_REQUEST = "FETCH_EVENT_ALLIANCES_REQUEST";
export const FETCH_EVENT_ALLIANCES_SUCCESS = "FETCH_EVENT_ALLIANCES_SUCCESS";
export const FETCH_EVENT_ALLIANCES_ERROR = "FETCH_EVENT_ALLIANCES_ERROR";
export const FETCH_MATCH_REQUEST = "FETCH_MATCH_REQUEST";
export const FETCH_MATCH_SUCCESS = "FETCH_MATCH_SUCCESS";
export const FETCH_MATCH_ERROR = "FETCH_MATCH_ERROR";
export const FETCH_ALL_TEAMS_REQUEST = "FETCH_ALL_TEAMS_REQUEST";
export const FETCH_ALL_TEAMS_SUCCESS = "FETCH_ALL_TEAMS_SUCCESS";
export const FETCH_ALL_TEAMS_ERROR = "FETCH_ALL_TEAMS_ERROR";
export const FETCH_ALL_EVENTS_REQUEST = "FETCH_ALL_EVENTS_REQUEST";
export const FETCH_ALL_EVENTS_SUCCESS = "FETCH_ALL_EVENTS_SUCCESS";
export const FETCH_ALL_EVENTS_ERROR = "FETCH_ALL_EVENTS_ERROR";
export const FETCH_EVENT_RANKINGS_REQUEST = "FETCH_EVENT_RANKINGS_REQUEST";
export const FETCH_EVENT_RANKINGS_SUCCESS = "FETCH_EVENT_RANKINGS_SUCCESS";
export const FETCH_EVENT_RANKINGS_ERROR = "FETCH_EVENT_RANKINGS_ERROR";
