// App
export const TOGGLE_THEME = "TOGGLE_THEME";

// Fetching
export const FETCH_YEAR_EVENTS_REQUEST = "FETCH_YEAR_EVENTS_REQUEST";
export const FETCH_YEAR_EVENTS_SUCCESS = "FETCH_YEAR_EVENTS_SUCCESS";
export const FETCH_YEAR_EVENTS_ERROR = "FETCH_YEAR_EVENTS_ERROR";
export const FETCH_EVENT_REQUEST = "FETCH_EVENT_REQUEST";
export const FETCH_EVENT_SUCCESS = "FETCH_EVENT_SUCCESS";
export const FETCH_EVENT_ERROR = "FETCH_EVENT_ERROR";
export const FETCH_EVENT_MATCHES_REQUEST = "FETCH_EVENT_MATCHES_REQUEST";
export const FETCH_EVENT_MATCHES_SUCCESS = "FETCH_EVENT_MATCHES_SUCCESS";
export const FETCH_EVENT_MATCHES_ERROR = "FETCH_EVENT_MATCHES_ERROR";
