name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          version: 10
      - name: Install
        run: npm install
      - name: Test
        env:
          CI: "true"
        run: npm test
      - name: Check lint
        run: npm run lint
      - name: Check formatting
        run: npm run prettier
      - name: Build
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          STACKDRIVER_API_KEY: ${{ secrets.STACKDRIVER_API_KEY }}
          TBA_API_AUTH_KEY: ${{ secrets.TBA_API_AUTH_KEY }}
        run: npm run build
      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          version: 10
      - name: Is not [nodeploy]
        uses: ./.github/actions/filter-commit-message
        with:
          args: -n \[nodeploy\]
      - name: Install
        run: npm install
      - name: Build
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          STACKDRIVER_API_KEY: ${{ secrets.STACKDRIVER_API_KEY }}
          TBA_API_AUTH_KEY: ${{ secrets.TBA_API_AUTH_KEY }}
        run: npm run build
      - name: Authenticate Google Cloud
        uses: actions/gcloud/auth@ba93088eb19c4a04638102a838312bb32de0b052
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      - name: Deploy
        uses: actions/gcloud/cli@ba93088eb19c4a04638102a838312bb32de0b052
        with:
          args: app deploy --project tbatv-prod-hrd --version 1 --quiet
