name: "Filter commit message"
description: "Stop a workflow if the message of the current commit doesn't match the pattern"
inputs:
  args:
    description: "args"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.args }}
